# Generated by Django 2.2.7 on 2019-12-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='verified',
        ),
    ]
